#!/usr/bin/env sh

# install compiler
npm install -g purescript
# install builder
npm install -g pulp bower
# create a new project
pulp init
pulp build
pulp test
bower install purescript-lists --save
echo /bower_components/ > .gitignore
